package DefinicionInterfaz.Administradores;


/**
* Administradores/Administrador.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Administrador.idl
* viernes 9 de noviembre de 2018 05:48:08 PM COT
*/

public interface Administrador extends  AdministradorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Administrador
