package Juegos;


/**
* Juegos/juego.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Juego.idl
* domingo 11 de noviembre de 2018 04:08:47 PM COT
*/

public interface juego extends juegoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface juego
