package Juegos;


/**
* Juegos/juegoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Juego.idl
* domingo 11 de noviembre de 2018 04:08:47 PM COT
*/

public abstract class juegoPOA extends org.omg.PortableServer.Servant
 implements Juegos.juegoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarVentajuego", new java.lang.Integer (0));
    _methods.put ("actualizarVentajuego", new java.lang.Integer (1));
    _methods.put ("eliminarVentajuego", new java.lang.Integer (2));
    _methods.put ("consultarVentajuego", new java.lang.Integer (3));
    _methods.put ("shoutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Juegos/juego/insertarVentajuego
       {
         int id = in.read_long ();
         String nombre = in.read_wstring ();
         String nombreJuego = in.read_wstring ();
         String generoJuego = in.read_wstring ();
         int subtotal = in.read_long ();
         int cantidad = in.read_long ();
         int totalPagar = in.read_long ();
         boolean $result = false;
         $result = this.insertarVentajuego (id, nombre, nombreJuego, generoJuego, subtotal, cantidad, totalPagar);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Juegos/juego/actualizarVentajuego
       {
         int id = in.read_long ();
         String nombre = in.read_wstring ();
         String nombreJuego = in.read_wstring ();
         String generoJuego = in.read_wstring ();
         int subtotal = in.read_long ();
         int cantidad = in.read_long ();
         int totalPagar = in.read_long ();
         boolean $result = false;
         $result = this.actualizarVentajuego (id, nombre, nombreJuego, generoJuego, subtotal, cantidad, totalPagar);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Juegos/juego/eliminarVentajuego
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarVentajuego (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Juegos/juego/consultarVentajuego
       {
         int id = in.read_long ();
         String $result = null;
         $result = this.consultarVentajuego (id);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Juegos/juego/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Juegos/juego:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public juego _this() 
  {
    return juegoHelper.narrow(
    super._this_object());
  }

  public juego _this(org.omg.CORBA.ORB orb) 
  {
    return juegoHelper.narrow(
    super._this_object(orb));
  }


} // class juegoPOA
