package DefinicionInterfaz.Juegos;

/**
* VentasJuegos/VentajuegoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VentaJuego.idl
* domingo 11 de noviembre de 2018 02:20:52 AM COT
*/

public final class VentajuegoHolder implements org.omg.CORBA.portable.Streamable
{
  public DefinicionInterfaz.Juegos.Ventajuego value = null;

  public VentajuegoHolder ()
  {
  }

  public VentajuegoHolder (DefinicionInterfaz.Juegos.Ventajuego initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DefinicionInterfaz.Juegos.VentajuegoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DefinicionInterfaz.Juegos.VentajuegoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DefinicionInterfaz.Juegos.VentajuegoHelper.type ();
  }

}
