package DefinicionInterfaz.Juegos;


/**
* VentasJuegos/Ventajuego.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VentaJuego.idl
* domingo 11 de noviembre de 2018 02:20:52 AM COT
*/

public interface Ventajuego extends VentajuegoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Ventajuego
