package DefinicionInterfaz.VentaJuegos;


/**
* VentasJuegos/_VentajuegoStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VentaJuego.idl
* domingo 11 de noviembre de 2018 02:20:52 AM COT
*/

public class _VentajuegoStub extends org.omg.CORBA.portable.ObjectImpl implements DefinicionInterfaz.VentaJuegos.Ventajuego
{

  public boolean insertarVentajuego (int nombre, String nombreJuego, String generoJuego, String precio, String cantidad, String total)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarVentajuego", true);
                $out.write_long (nombre);
                $out.write_wstring (nombreJuego);
                $out.write_wstring (generoJuego);
                $out.write_wstring (precio);
                $out.write_wstring (cantidad);
                $out.write_wstring (total);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarVentajuego (nombre, nombreJuego, generoJuego, precio, cantidad, total        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarVentajuego

  public boolean actualizarVentajuego (int nombre, String nombreJuego, String generoJuego, String precio, String cantidad, String total)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarVentajuego", true);
                $out.write_long (nombre);
                $out.write_wstring (nombreJuego);
                $out.write_wstring (generoJuego);
                $out.write_wstring (precio);
                $out.write_wstring (cantidad);
                $out.write_wstring (total);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarVentajuego (nombre, nombreJuego, generoJuego, precio, cantidad, total        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarVentajuego

  public boolean eliminarVentajuego (int nombre)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarVentajuego", true);
                $out.write_long (nombre);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarVentajuego (nombre        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarVentajuego

  public String consultarVentajuego (int nombre)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarVentajuego", true);
                $out.write_long (nombre);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarVentajuego (nombre        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarVentajuego

  public void shoutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shoutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shoutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shoutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:VentasJuegos/Ventajuego:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _VentajuegoStub
