package DefinicionInterfaz.VentaJuegos;


/**
* VentasJuegos/VentajuegoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VentaJuego.idl
* domingo 11 de noviembre de 2018 02:20:52 AM COT
*/

public interface VentajuegoOperations 
{
  boolean insertarVentajuego (int nombre, String nombreJuego, String generoJuego, String precio, String cantidad, String total);
  boolean actualizarVentajuego (int nombre, String nombreJuego, String generoJuego, String precio, String cantidad, String total);
  boolean eliminarVentajuego (int nombre);
  String consultarVentajuego (int nombre);
  void shoutdown ();
} // interface VentajuegoOperations
