module VentasJuegos{
    interface Ventajuego{
        boolean insertarVentajuego( in long id, in wstring nombre, in wstring nombreJuego, in wstring generoJuego, in long precio , in long cantidad);
        boolean actualizarVentajuego( in long id, in wstring nombre, in wstring nombreJuego, in wstring generoJuego, in long precio , in long cantidad);
        boolean eliminarVentajuego(in long id);
        wstring consultarVentajuego(in long id);

        oneway void shoutdown();
    };
};

